# Generated by Django 4.1.2 on 2022-10-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='note',
            name='no_of_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
