# Generated by Django 4.1.2 on 2022-10-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='username',
            new_name='creator',
        ),
    ]
