# Generated by Django 4.1.2 on 2022-10-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_username_like_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='note_id',
        ),
    ]
