# Generated by Django 4.1.2 on 2022-10-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_post_id_like_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
