# Generated by Django 4.1.2 on 2022-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_note_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
