# Generated by Django 4.1.2 on 2022-10-23 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_creator_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.RemoveField(
            model_name='note',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
