# Generated by Django 4.1.2 on 2022-11-01 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_like_remove_note_no_of_likes_note_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
