# Generated by Django 4.1.2 on 2022-11-03 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
